name: 'Release Developer SSh Server'

on:
  push:
    tags:
      - v**-ssh

jobs:
  build-docker-image:
    runs-on: self-hosted
    outputs:
      image_tag: ${{ fromJSON(steps.meta.outputs.json).tags[0] }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          logout: true
          registry: ${{ secrets.REGISTRY_URI }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.REGISTRY_URI }}/genius-auth/ssh-server

      - name: Build Docker Image and Push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          file: ./Dockerfile.ssh
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    needs: build-docker-image
    runs-on: self-hosted
    steps:
      - name: Update Prod Deployment
        uses: MultiMx/K8sSetImageAction@v0.5
        if: ${{ !contains(github.ref, 'beta') }}
        with:
          backend: ${{ secrets.CATTLE_URL }}
          token: ${{ secrets.CATTLE_TOKEN }}
          namespace: 'genius-auth'
          workload: 'ssh-server'
          image: ${{ needs.build-docker-image.outputs.image_tag }}